### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by ghost** [itwangyu/NovelReaderAdDemo#1]
下载运行了一下，缺少布局文件layout_ad_view，layout_ad_view2，以及jar包和工具类UtilsView，求补全

**Comment by itwangyu** [comment]
已经补全，并且加入了广点通广告

**Comment by fcscr126608** [comment]
@itwangyu 
![image](https://user-images.githubusercontent.com/35981460/50197738-69ac2800-0383-11e9-8fdf-c58d25857ae4.png)
