### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ghost** [itwangyu/NovelReaderAdDemo#2]
![image](https://user-images.githubusercontent.com/35981460/50259354-b7d23180-043e-11e9-9ce4-e90362dd4db9.png)
这里运行报错。
问一下，如果想在每一章的最后一页后面添加一页用来放广告，思路大概是怎么样，感谢！

**Comment by itwangyu** [comment]
![image](https://user-images.githubusercontent.com/13809977/50322369-b9b7f580-050f-11e9-921a-dcb77b80341c.png)
就是在我画红线这个位置，给pages这个list添加一个标记为广告的TxtPage即可

**Comment by ghost** [comment]
你好，滚动翻页模式下无法点击弹出的广告，请教如何解决？
